### ISSUE TITLE
Am i missing something

### ISSUE THREAD

**Issue by ChrisCopter** [Opinionated-Blueprints/10-Books-Full-of-Rails#10]
Thank you for all the work you put into this first of all.

My issue is, that i dont see as many Prints in the book, as you mentioned in the discription.
Sorry if this is dumb, to long playing factorio :D

![grafik](https://github.com/user-attachments/assets/862e23f0-0085-493b-afc7-7d44a505f474)

**Comment by TConnor2003** [comment]
This book was originally made for the old version of factorio. Since the update to 2.0 all rail blueprints needed to be redone. It's being worked on and new updates are coming as the author makes them

**Comment by rpdelaney** [comment]
> My issue is, that i dont see as many Prints in the book, as you mentioned in the discription.

What's the question?

**Comment by Xiarno** [comment]
> > My issue is, that i dont see as many Prints in the book, as you mentioned in the discription.
> 
> What's the question?

I believe TConnors2003 answered it pretty well. OP thought many blueprints were missing from the description on the page about the blueprint, but it's just that the reason are it's the new 2.0 blueprint which doesn't have as many blueprint as the previous version since it's still being updated.
