### ISSUE TITLE
Missing some decider combiners on inline providers?

### ISSUE THREAD

**Issue by AJarOfDirt0** [Opinionated-Blueprints/10-Books-Full-of-Rails#101]
### Have you checked the following resources?

- [X] [Wiki](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/wiki)
- [X] [Discussions Forum](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/discussions)
- [X] [Open and Closed Issues](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/issues)

### Version of the Book

v2.22.0

### Bug Description

Train limit isn't being set on inline providers

### How to reproduce the problem

Make an inline provider

### What did you expect?

Train limit would be set correctly

### What happened instead?

It wasn't

**Comment by Bocian-1** [comment]
Fixed on [v2.22.1](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/releases/tag/v2.22.1).
It wasn't a missing combinator but a wire and the stops had 'set train limit' enabled when the shouldn't since there are no stackers anyway
