### ISSUE TITLE
Explain the fuel system

### ISSUE THREAD

**Issue by beppe86** [Opinionated-Blueprints/10-Books-Full-of-Rails#14]
What is the difference between Fuel Supply and Refuelling Station?
Some of the book documentation mentions supplier station, which one is that?

My train seems to correctly go to the Refuelling Station when it is low on fuel but stops at the station before the green one so nothing gets moved onto the train.
Maybe the refueling system could be explained a little bit more thorough?

Thanks for a wonderful project that I appreciate heavily!

**Comment by Bocian-1** [comment]
The `Fuel Supply` and the Green Station in the `Refuelling Station` blueprint are only for the `Refuel Train`, while the Black Station in the same blueprint is the actual refuelling station for the rest of your trains.

The idea is that you place the `Fuel Supply` somewhere near your current fuel production (or alternatively deliver the fuel to it), and then can have multiple `Refuelling Stations` spread across your network. The `Refuel Train` should keep all the `Refuel Stations` supplied.

Additionally, if the `Fuel Supply` receives a new type of fuel that has a higher priority (by default it's some vanilla fuels ordered by fuel value, which can be changed by editing the constant combinator group), it will clear the belt of the old fuel and load it up into the other chest like in the video below. 
https://github.com/user-attachments/assets/e788351a-ca42-4ebf-87db-737b6f933b4d

When a higher-priority type of fuel is supplied via the `Refuel Train` to a `Refuelling Station`, the old fuel will be dumped out of the buffer at the station and brought back to the `Fuel Supply`, where it will be unloaded into the same chest mentioned above. Incoming locomotives including the `Refuel Train's` will also be emptied of their old fuel to make room for the new one and the old fuel will be brought back in the next supply run.
https://github.com/user-attachments/assets/eb0f2402-1e55-44f6-9624-3cfd1f80501a

What happens after the old fuel is put in the dedicated chest at `Fuel Supply` is up to you, but you need to take care of it somehow.

All that said, this is all pretty new, and might still have some issues even though I've tested it somewhat thoroughly by now.

**Comment by DBosley** [comment]
refuelling1.mp4 is failing to load for me.

**Comment by beppe86** [comment]
Thanks for the description, I will try and get it to work
