### ISSUE TITLE
Pictures

### ISSUE THREAD

**Issue by Bocian-1** [Opinionated-Blueprints/10-Books-Full-of-Rails#2]
![Rails - non-solar](https://user-images.githubusercontent.com/70019596/106368255-9e538180-6348-11eb-955d-388e757714ec.png)
![2 Lane](https://user-images.githubusercontent.com/70019596/106368261-a6abbc80-6348-11eb-98d8-0dfe3476df0b.png)
![4 Lane](https://user-images.githubusercontent.com/70019596/103366614-6516c000-4ac3-11eb-85a3-4aaab788c4db.png)
![Entrances-Exits](https://user-images.githubusercontent.com/70019596/104123891-e7b63f80-534d-11eb-8eef-d1fe9f8d1384.png)
![Entrances-Exits Diagonal](https://user-images.githubusercontent.com/70019596/104123892-ea189980-534d-11eb-802f-53ffa8a9e12a.png)
![4;2;1 Lane](https://user-images.githubusercontent.com/70019596/106368271-b1fee800-6348-11eb-9124-0a4a7b42793d.png)
![4;2;1 Lane Diagonal](https://user-images.githubusercontent.com/70019596/106368274-bc20e680-6348-11eb-882a-9b716e6efef5.png)
![2 4 Lane Split Junctions](https://user-images.githubusercontent.com/70019596/103184237-72f7f580-48b7-11eb-8120-c384a833436a.png)
![Stations - Vanilla](https://user-images.githubusercontent.com/70019596/152643032-4d3e9b68-ad39-4577-a181-9536622db968.png)
![Wall Yoga](https://user-images.githubusercontent.com/70019596/106266452-b9c76b00-6228-11eb-9fc9-6e45222ec9b6.png)
![Twister](https://github.com/user-attachments/assets/c7764d58-c3b2-4244-8c4b-2e7c6d708597)
![Dogbone](https://github.com/user-attachments/assets/d7539f62-7264-4ce7-b12a-d65fdbb7734c)
![Superstreet](https://github.com/user-attachments/assets/40aea9bf-b97c-49f8-9fb6-d2b46add965d)
![Diverging Diamond](https://github.com/user-attachments/assets/eae2460c-ae9e-4207-b8bb-49c5b0f75b11)
![2-Level Diverging Diamond](https://github.com/user-attachments/assets/44d6009e-7e50-4caa-a600-7c5aa2aebe9c)
![Double Crossover Diamond](https://github.com/user-attachments/assets/77f5c2a1-73bb-4aa4-aff4-34a43b942da1)
![Cloverleaf](https://github.com/user-attachments/assets/cf78988d-82eb-4970-aa11-fa7dcd67cff6)
![Partially Unrolled Cloverleaf](https://github.com/user-attachments/assets/96c6c314-ddd5-4828-821c-a18a5045730e)
![Inside Turning Left](https://github.com/user-attachments/assets/597bf9c7-39c5-4296-8dc0-fd04560ae3d5)
![Celtic Knot](https://github.com/user-attachments/assets/d5a9a891-2734-4703-92ef-e99bb4d213ae)
![Buffered Celtic Knot](https://github.com/user-attachments/assets/43bad643-4e7c-4742-b79e-cdc07d9705d4)
![Whirlpool](https://github.com/user-attachments/assets/376c359f-2951-4213-9bed-f3cbe23554b2)
![Windmill (A)](https://github.com/user-attachments/assets/6a300f98-a171-4b56-82d2-9734dc0f238e)
![Windmill (B)](https://github.com/user-attachments/assets/9ea0bcb5-53e5-40db-bc81-06f79bd6d78e)
![Pinwheel](https://github.com/user-attachments/assets/5c5bbaab-1151-4f37-99d7-dc0fb1fc145a)
![Trumpet](https://github.com/user-attachments/assets/4f563745-3540-4472-939e-b1cae52252d3)
![Bottle](https://github.com/user-attachments/assets/ed61053f-04fd-48da-bb20-876c7e982a6d)
![3-way Cloverleaf (A)](https://github.com/user-attachments/assets/5f15bdb8-abf9-45f9-9115-0334804ded92)
![3-way Cloverleaf (B)](https://github.com/user-attachments/assets/52011f58-2495-48c1-8894-c5ffd60cbe13)
![Compact 3-way](https://github.com/user-attachments/assets/cdedd113-6a08-40fb-9439-550e00ce64b9)

**Comment by rpdelaney** [comment]
I hope to get the build system generating these diagrams. One can dream :)

**Comment by Fevix** [comment]
Space Age released today why aren't these blueprints already updated!?!

(I'm joking :P)

**Comment by Xiarno** [comment]
> Space Age released today why aren't these blueprints already updated!?!
> 
> (I'm joking :P)

Honestly I wouldn't have been surprised if they got the release early to work on this blueprint. But I guess they haven't or/and they haven't finished. But it's okay! We'll wait for it. Simply the best rail book blueprint I've ever used! It actually made me use rail whereas before I didn't use them as much.

**Comment by Bocian-1** [comment]
Yeah, we didn't get anything early, though it would've been pretty nice!
I've had a few busy days still, but I'm mostly free for the rest of the week so I'll be getting something done soon(TM)
I've made and tested a few interchanges already
https://factoriobin.com/post/s3cxf87sithz-EXPIRES

**Comment by Bocian-1** [comment]
Closing. It's all outdated now.
