### ISSUE TITLE
Your latest release is just the Stations book

### ISSUE THREAD

**Issue by ShaneYu** [Opinionated-Blueprints/10-Books-Full-of-Rails#20]
### Have you checked the following resources?

- [X] [Wiki](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/wiki)
- [X] [Discussions Forum](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/discussions)
- [X] [Open and Closed Issues](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/issues)

### Version of the Book

2.7.0

### Bug Description

Latest 2.7.0 release is only the Stations book

### How to reproduce the problem

Import release 2.7.0 into Factorio. I believe that you've accidently exported the Stations book opposed to the main book up a level.

Work around for any one wanting latest is to use the previous version, delete out the stations book and then import the new stations book (which is release 2.7.0) and then add that book back into the main one.

### What did you expect?

All of the rail book (including all sub books)

### What happened instead?

Only the stations sub book.

**Comment by Bocian-1** [comment]
My bad. I've replaced the file for 2.7.0 with the correct one.
