### ISSUE TITLE
Infinite load/unload of refuel train with single type of fuel.

### ISSUE THREAD

**Issue by Xeinaemm** [Opinionated-Blueprints/10-Books-Full-of-Rails#23]
### Have you checked the following resources?

- [X] [Wiki](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/wiki)
- [X] [Discussions Forum](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/discussions)
- [X] [Open and Closed Issues](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/issues)

### Version of the Book

v2.6.0

### Bug Description

Refuel trains are stuck in an infinite loop at refueling stations when using only one type of fuel for trains and wagons without having any other fuel types.

### How to reproduce the problem

Place new and empty refueling station. Set a train to use identical fuel with delivering one. Delivering fuel to the station ends in an infinite loop.
![loop](https://github.com/user-attachments/assets/6a502e5a-9a5b-4cdc-8075-947acc2a6804)

### What did you expect?

Unload fuel and go.

### What happened instead?

Infinite loop of load/unload

**Comment by Bocian-1** [comment]
Fixed as of 2.8.0, thank you for the report.
