### ISSUE TITLE
Solar / Non-Solar Entry underpass misaligned to chunk on horizontal axis

### ISSUE THREAD

**Issue by FelkonEx** [Opinionated-Blueprints/10-Books-Full-of-Rails#25]
### Have you checked the following resources?

- [X] [Wiki](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/wiki)
- [X] [Discussions Forum](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/discussions)
- [X] [Open and Closed Issues](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/issues)

### Version of the Book

2.9.0

### Bug Description

Solar / Non-Solar Entry Underpass blueprint doesn't align with chunk for straight rails on the horizontal axis

### How to reproduce the problem

1. Place straight rail blueprint down horizontally
2. Open Solar & Non-Solar Entry Underpass blueprint and view it misaligned with straight rail blueprint.

Pictures:
![2024-11-10_16-15-07_Factorio_Space_Age_2 0 15_](https://github.com/user-attachments/assets/24fa6f1c-d2ab-4526-aeff-b8f0068a3136)
![2024-11-10_16-15-03_Factorio_Space_Age_2 0 15_](https://github.com/user-attachments/assets/d2316b2e-35c3-44f2-8231-4fd61b3b5444)

Note: Vertical rails are OK, it's just the Horizontal rails

### What did you expect?

To be aligned like the Exit Underpass

### What happened instead?

Misaligned to chunk straight rails horizontally

**Comment by Bocian-1** [comment]
fixed in v2.9.1, thank you for the report
