### ISSUE TITLE
mixed items

### ISSUE THREAD

**Issue by cyborg728** [Opinionated-Blueprints/10-Books-Full-of-Rails#26]
### Have you checked the following resources?

- [X] [Wiki](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/wiki)
- [X] [Discussions Forum](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/discussions)
- [X] [Open and Closed Issues](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/issues)

### Version of the Book

2.9.0

### Bug Description

the items were mixed

### How to reproduce the problem

![image](https://github.com/user-attachments/assets/6f54e197-2fab-4287-9dff-a70e8c518aa9)
Rails-Stations-Inline Requesters-1-1-0 Train 3 Stations

### What did you expect?

unmixed items

### What happened instead?

the items were mixed

**Comment by Bocian-1** [comment]
fixed in v2.9.1, thank you for reporting
