### ISSUE TITLE
2-4-0 inline provider missing wires

### ISSUE THREAD

**Issue by elias098** [Opinionated-Blueprints/10-Books-Full-of-Rails#29]
### Have you checked the following resources?

- [X] [Wiki](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/wiki)
- [X] [Discussions Forum](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/discussions)
- [X] [Open and Closed Issues](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/issues)

### Version of the Book

2.11.1

### Bug Description

the 2-4-0 inline 3 station provider is missing red and green wires between medium poles in the middle station

### How to reproduce the problem

place inline 3 station provider

### What did you expect?

wires to be connected

### What happened instead?

wires arent connected

**Comment by Bocian-1** [comment]
fixed with v2.12.0. Thank you for reporting
