### ISSUE TITLE
Missing wiring on requesters 1/side (L) and 1/side (R)

### ISSUE THREAD

**Issue by Veraokulo** [Opinionated-Blueprints/10-Books-Full-of-Rails#30]
### Have you checked the following resources?

- [X] [Wiki](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/wiki)
- [X] [Discussions Forum](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/discussions)
- [X] [Open and Closed Issues](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/issues)

### Version of the Book

V2.11.1

### Bug Description

Missing wiring on requesters 1/side (L) and 1/side (R)

### How to reproduce the problem

Open Rails=>Stations=>Requesters

### What did you expect?

wiring

### What happened instead?

no wiring

**Comment by Bocian-1** [comment]
fixed with v2.12.0. Thank you for reporting

**Comment by mkaito** [comment]
Does not seem to be fixed in v2.12.0

**Comment by Bocian-1** [comment]
> Does not seem to be fixed in v2.12.0

My bad, I fixed some missing wiring on inline requesters and thought it was this for some reason. Fixed for real on v2.13.0
