### ISSUE TITLE
Inline Fluid 3-1 Requester Station pumps don't empty last wagon

### ISSUE THREAD

**Issue by brandon-gradient** [Opinionated-Blueprints/10-Books-Full-of-Rails#41]
### Have you checked the following resources?

- [X] [Wiki](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/wiki)
- [X] [Discussions Forum](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/discussions)
- [X] [Open and Closed Issues](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/issues)

### Version of the Book

v2.16.0

### Bug Description

Last wagon doesn't align with pumps leaving last wagon full of fluid

### How to reproduce the problem

Place the 3-1 fluid inline requester station (and likely 3-3 but not tested) and fill up a 1-2-0 fluid train and when it gets to the requester it won't align to empty the last wagon leaving it stuck at the requester station.

Also same station blueprint wasn't calculating the W*V (train cap?) parameter correctly, stayed at -3, and I had to manually change to 100k to get it to work. (didn't test 3-3 BP)

### What did you expect?

Both fluid wagons to empty at stop

### What happened instead?

Only first wagon emptied. Had to manually move train to get it to empty.

**Comment by Bocian-1** [comment]
Fixed in [v2.17.0](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/releases/tag/v2.17.0)
