### ISSUE TITLE
Inline Provider is missing cables

### ISSUE THREAD

**Issue by Jared87** [Opinionated-Blueprints/10-Books-Full-of-Rails#42]
### Have you checked the following resources?

- [ ] [Wiki](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/wiki)
- [ ] [Discussions Forum](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/discussions)
- [ ] [Open and Closed Issues](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/issues)

### Version of the Book

v2.16.0

### Bug Description

On the middle Station the red/green cable between the chests and the station is missing. So it never gets visited.

### How to reproduce the problem

![image](https://github.com/user-attachments/assets/f6771b44-3236-4700-958e-2409111911fd)

### What did you expect?

Trains collecting goods from this station

### What happened instead?

It gets ignored, because it cannot calculate the train limit

**Comment by Bocian-1** [comment]
Fixed in [v2.17.0](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/releases/tag/v2.17.0)
