### ISSUE TITLE
Wrong blueprint

### ISSUE THREAD

**Issue by Ada-TheFox** [Opinionated-Blueprints/10-Books-Full-of-Rails#44]
### Have you checked the following resources?

- [ ] [Wiki](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/wiki)
- [ ] [Discussions Forum](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/discussions)
- [ ] [Open and Closed Issues](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/issues)

### Version of the Book

2.16.0

### Bug Description

Blueprint of Inline Requester 1-2-0 (L) is a just a 2-4-0 (L). They are the same.

### How to reproduce the problem

![factorio](https://github.com/user-attachments/assets/98f25b43-128f-4408-89f4-edb67584d391)

### What did you expect?

A blueprint of Inline Requester 1-2-0 (L)

### What happened instead?

A blueprint of Inline Requester 2-4-0 (L)

**Comment by Bocian-1** [comment]
Fixed [v2.17.0](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/releases/tag/v2.17.0)
