### ISSUE TITLE
Brief description of the blueprint issue

### ISSUE THREAD

**Issue by hashiqi165** [Opinionated-Blueprints/10-Books-Full-of-Rails#45]
### Have you checked the following resources?

- [X] [Wiki](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/wiki)
- [X] [Discussions Forum](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/discussions)
- [X] [Open and Closed Issues](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/issues)

### Version of the Book

v.2.17.0

### Bug Description

Provider Solids Signal error

### How to reproduce the problem

![QQ20241116-220206](https://github.com/user-attachments/assets/ede47285-811c-4eb9-9b4f-49954adeb96e)
![QQ20241116-220215](https://github.com/user-attachments/assets/15371ee1-9fef-41cf-a7cd-f5f6ec0be9f9)
![QQ20241116-220235](https://github.com/user-attachments/assets/5a44ef5c-9c69-4aab-ab70-fbb338122b3f)
Should it be modified to look like this?

### What did you expect?

.

### What happened instead?

.

**Comment by Bocian-1** [comment]
Quick find! Fixed in [v2.17.1](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/releases/tag/v2.17.1)
