### ISSUE TITLE
Brief description of the blueprint issue

### ISSUE THREAD

**Issue by hashiqi165** [Opinionated-Blueprints/10-Books-Full-of-Rails#46]
### Have you checked the following resources?

- [X] [Wiki](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/wiki)
- [X] [Discussions Forum](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/discussions)
- [X] [Open and Closed Issues](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/issues)

### Version of the Book

v.2.17.1

### Bug Description

Provider Solids Signal error

### How to reproduce the problem

![QQ20241116-225736](https://github.com/user-attachments/assets/781d7613-2d6c-4fa8-8cf8-3271ffc2a5c2)
The red line signal L is changed to the signal T

### What did you expect?

.

### What happened instead?

.

**Comment by hashiqi165** [comment]
![Uploading QQ20241116-220206.png…]()
Or change the output in this combinator to the signal L

**Comment by Bocian-1** [comment]
Fiuxed in [v2.17.2](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/releases/tag/v2.17.2)
