### ISSUE TITLE
Brief description of the blueprint issue

### ISSUE THREAD

**Issue by TommyRush** [Opinionated-Blueprints/10-Books-Full-of-Rails#47]
### Have you checked the following resources?

- [X] [Wiki](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/wiki)
- [X] [Discussions Forum](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/discussions)
- [X] [Open and Closed Issues](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/issues)

### Version of the Book

2.17.1

### Bug Description

Solids provider doesn't fit in 6 car outpost double

### How to reproduce the problem

The solids provider doesn't fit in the middle station on the 6 car double outpost because the far right arithmetic calculator in the provider is being blocked by the curved track. The liquid provider does fit. I didn't try the other car lengths. 
![factorio](https://github.com/user-attachments/assets/c40dfe7b-d466-4d4e-904a-6e37aa82d5a2)

Thanks for the blueprints!

### What did you expect?

Solids provider fits both stations in the 6 car outpost double

### What happened instead?

Solids provider doesn't fit the middle station

**Comment by Bocian-1** [comment]
Fixed in [v2.17.2](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/releases/tag/v2.17.2)
