### ISSUE TITLE
Diagonal wall blueprints don't align anymore

### ISSUE THREAD

**Issue by dp-alvarez** [Opinionated-Blueprints/10-Books-Full-of-Rails#49]
### Have you checked the following resources?

- [X] [Wiki](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/wiki)
- [X] [Discussions Forum](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/discussions)
- [X] [Open and Closed Issues](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/issues)

### Version of the Book

2.17.3

### Bug Description

The diagonal wall blueprints don't connect anymore. I suspect it is only a matter of adjusting the blueprint grid

### How to reproduce the problem

![2024-11-16_20-47](https://github.com/user-attachments/assets/e2859ffc-40ec-4c1b-8f27-a4249c3a70f4)

### What did you expect?

This feels like a redundant field

### What happened instead?

This feels like a redundant field

**Comment by dp-alvarez** [comment]
I don't think it is only a matter of adjusting the grid of the corner piece. I tried doing that and the wires don't connect, plus some wall pieces look out of place.

![2024-11-16_20-56](https://github.com/user-attachments/assets/6ef3ab3c-6486-4d11-8361-607b71314306)

**Comment by Bocian-1** [comment]
What do I have with walls and updating them by accident...
Well, I wouldn't recommend using them either way. They're too weak for 100%evo and I shouldn't have ever added them to begin with

**Comment by Bocian-1** [comment]
> I don't think it is only a matter of adjusting the grid of the corner piece. I tried doing that and the wires don't connect, plus some wall pieces look out of place.

This is how the diagonal walls would be placed, with diagonal and diagonal (corner) alternating.
![image](https://github.com/user-attachments/assets/74331ccc-56d9-44a1-bceb-763e17cfc4e5)

**Comment by dp-alvarez** [comment]
My mistake, I was adjusting the grid of the main diagonal piece instead of the corner one.

Also, don't underestimate how useful those are! Even if they can't survive full evo, it is plenty enough for many players given artillery and laser damage upgrades. Having them pre-made and working with the main train grid is a huge time saver and makes everything look nice.

I'd personally love to see upgradeable wall blueprints: The first version being a single-layer wall with sparse turrets, that you can paste over to make it beefier over time and maybe add things like flamethrowers or artillery.

Thanks for the blueprints, they are beautifully designed and incredibly complete.

**Comment by Bocian-1** [comment]
Reworked walls in [v2.18.0](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/releases/tag/v2.18.0). Now they're good for 100%evo on Nauvis, but the design is completely different
