### ISSUE TITLE
Bufferless 1-2-0 providers have a power pole one tile off

### ISSUE THREAD

**Issue by dp-alvarez** [Opinionated-Blueprints/10-Books-Full-of-Rails#50]
### Have you checked the following resources?

- [x] [Wiki](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/wiki)
- [x] [Discussions Forum](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/discussions)
- [x] [Open and Closed Issues](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/issues)

### Version of the Book

2.17.3

### Bug Description

As per picture

### How to reproduce the problem

![2024-11-17_03-08](https://github.com/user-attachments/assets/5a4b81f4-df87-45d7-a391-1b482ca83236)

### What did you expect?

Yes

### What happened instead?

Yes

**Comment by Bocian-1** [comment]
Fixed in [v2.18.0](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/releases/tag/v2.18.0)
