### ISSUE TITLE
Elevated T intersection has unnecessary rail supports

### ISSUE THREAD

**Issue by mkaito** [Opinionated-Blueprints/10-Books-Full-of-Rails#51]
### Have you checked the following resources?

- [X] [Wiki](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/wiki)
- [X] [Discussions Forum](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/discussions)
- [X] [Open and Closed Issues](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/issues)

### Version of the Book

v2.17.3

### Bug Description

Two extra diagonal supports on the flat side of the elevated T intersection

### How to reproduce the problem

Probably there from the 4-way intersection overlay.

### What did you expect?

Unnecessary supports to not be present

### What happened instead?

Unnecessary supports are present

**Comment by Bocian-1** [comment]
Fixed in [v2.18.0](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/releases/tag/v2.18.0)
