### ISSUE TITLE
Stray wooden power pole in hypermodular corner

### ISSUE THREAD

**Issue by dp-alvarez** [Opinionated-Blueprints/10-Books-Full-of-Rails#57]
### Have you checked the following resources?

- [ ] [Wiki](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/wiki)
- [ ] [Discussions Forum](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/discussions)
- [ ] [Open and Closed Issues](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/issues)

### Version of the Book

2.18.1

### Bug Description

Stray wooden power pole in hypermodular corner

### How to reproduce the problem

![2024-11-19_20-12](https://github.com/user-attachments/assets/40075450-d650-48d5-893c-bef75be802c7)

### What did you expect?

Stray wooden power pole in hypermodular corner

### What happened instead?

Stray wooden power pole in hypermodular corner

**Comment by Bocian-1** [comment]
Fixed with [v2.19.0](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/releases/tag/v2.19.0).
