### ISSUE TITLE
Elevated Entry/Exit Underpass Needs Chain Signal

### ISSUE THREAD

**Issue by crackalackintv** [Opinionated-Blueprints/10-Books-Full-of-Rails#62]
### Have you checked the following resources?

- [X] [Wiki](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/wiki)
- [X] [Discussions Forum](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/discussions)
- [X] [Open and Closed Issues](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/issues)

### Version of the Book

2.18.1

### Bug Description

-

### How to reproduce the problem

With the current iteration of the Elevated Entry/Exit Underpass, two trains can get deadlocked facing each other in the "exit" double-signal. Given this is intended to be a single-tracked exit, it needs a change in signaling as shown below.

Also, does putting down this blueprint over existing elevated rails break the straight rails and leaves gaps for anyone else as well? It is, pretty sure, a bot order issue, as it doesn't happen in the editor. 🤔 

EDIT: It needs two chain signals instead of my chain + normal to prevent a deadlock in the center.

![20241119144526_1](https://github.com/user-attachments/assets/70317cdd-de9d-4052-aab0-b14ff168c513)
![20241119144655_1](https://github.com/user-attachments/assets/4fe5afda-cb28-4024-a12b-a5e0b45a5444)

### What did you expect?

-

### What happened instead?

-

**Comment by Bocian-1** [comment]
Fixed (I think, I don't work with one-way enough...), with [v2.19.0](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/releases/tag/v2.19.0). Please reopen if I messed it up.
