### ISSUE TITLE
Possible Deadlock Entry/Exit Underpass

### ISSUE THREAD

**Issue by Zercerium** [Opinionated-Blueprints/10-Books-Full-of-Rails#65]
### Have you checked the following resources?

- [X] [Wiki](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/wiki)
- [X] [Discussions Forum](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/discussions)
- [X] [Open and Closed Issues](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/issues)

### Version of the Book

v2.18.1

### Bug Description

Possible Deadlock (see pictures)

### How to reproduce the problem

Hi, at first thanks for this great blueprint library. It makes playing with trains such an ease.

The following Deadlock can occur 
![Screenshot 2024-11-21 205624](https://github.com/user-attachments/assets/c73bfd1f-a32e-4d1e-9cd6-bd51a23d91a2)

This should be a fix:
- 4 signals changed to chain signals (yellow circles), so that no train from the main lane can enter and block the green exit paths
- blue trains cannot enter green paths until purple area is clear
- green lines aren't blocked, so purple train can leave

![image](https://github.com/user-attachments/assets/5b4a5597-0a8a-4cca-95fe-7cad2db08509)

### What did you expect?

No Deadlock

### What happened instead?

Deadlock

**Comment by Bocian-1** [comment]
Fixed (I think, I'm not too good with one-way tbh), with 2.19.0. Please reopen if I messed it up.
