### ISSUE TITLE
Constant combinator in fluid requirement doesn't work properly

### ISSUE THREAD

**Issue by Ella-Stingray** [Opinionated-Blueprints/10-Books-Full-of-Rails#68]
### Have you checked the following resources?

- [X] [Wiki](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/wiki)
- [X] [Discussions Forum](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/discussions)
- [X] [Open and Closed Issues](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/issues)

### Version of the Book

v2.19.0

### Bug Description

Constant combinator receives incorrect values

### How to reproduce the problem

Just using "Requester Fluids"
![settings](https://github.com/user-attachments/assets/860db21a-c4ae-4376-8684-9f4d0acabbae)
![result](https://github.com/user-attachments/assets/9df29b96-fcf2-4d1f-8152-4fb294e44a86)

### What did you expect?

Ready to use blueprint

### What happened instead?

The values “W” and “Requested fluid” are not correct

**Comment by Bocian-1** [comment]
Ah, of course I checked he solid one and not fluid
