### ISSUE TITLE
Rail alignment with Premade City Blocks

### ISSUE THREAD

**Issue by DragonsKeep89** [Opinionated-Blueprints/10-Books-Full-of-Rails#69]
### Have you checked the following resources?

- [X] [Wiki](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/wiki)
- [X] [Discussions Forum](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/discussions)
- [X] [Open and Closed Issues](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/issues)

### Version of the Book

2.19.1

### Bug Description

None of the rails align with the premade city blocks.

### How to reproduce the problem

Place any city block then try to place any other part of the rail book that is not a city block.
![20241122093917_1](https://github.com/user-attachments/assets/9339f0d3-6a1a-4fbb-b5be-8efbd9ceb353)

I have now made my entire base using the city blocks but when trying to line rails up for out posting nothing is working.

### What did you expect?

Alignment with all pieces.

### What happened instead?

City Blocks are on a different grid pattern.

**Comment by Bocian-1** [comment]
Fixed in v2.19.2. You'll need to use hypermodular rails to consistently match every connection point. Regular 42x42 rails only match every 3rd connection.

**Comment by DragonsKeep89** [comment]
Thank you for the quick help.
