### ISSUE TITLE
When importing, only the first drawing book is saved

### ISSUE THREAD

**Issue by Kaerius** [Opinionated-Blueprints/10-Books-Full-of-Rails#7]
When importing, only the first drawing book is saved

**Comment by Bocian-1** [comment]
This is what you should be getting right now. I'm only including the parts updated for 2.0/Space Age. The un-updated parts would be broken and unusable anyway.
 
![image](https://github.com/user-attachments/assets/d81ff11a-3a39-44de-82f3-578f8185a47b)
![image](https://github.com/user-attachments/assets/a200eb3f-7978-4473-a6ac-4f3c9c327b49)
