### ISSUE TITLE
Inverted logic for Wall Maintenance Requester Inserters

### ISSUE THREAD

**Issue by OldieButGoldie** [Opinionated-Blueprints/10-Books-Full-of-Rails#70]
### Have you checked the following resources?

- [X] [Wiki](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/wiki)
- [X] [Discussions Forum](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/discussions)
- [X] [Open and Closed Issues](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/issues)

### Version of the Book

v2.19.0

### Bug Description

The Wall maintenance requester does not work

### How to reproduce the problem

Setup the requester station and the inserters don't insert the bots into the roboports.

This is because the connected circuit logic compares "number of expected" robots (robot signals from combinator) with "number of total (real)" bots (T/Y signals) backwards. It only enables the inserter if the number of expected bots is less than the real number of bots which when setting a new outpost is 0, so the condition is never true.

![image](https://github.com/user-attachments/assets/4b81f546-ca53-4eb1-b32a-738ee9772ac7)

In addition, you could set up the stack size to 1 so the robots are exactly as requested.

### What did you expect?

Bootstrapping the wall requester works

### What happened instead?

Bootstrapping the wall requester doesn't work

**Comment by Bocian-1** [comment]
Ah yes, my seemingly never-ending ability to test things in ways that don't find the most obvious of issues at full display once again

**Comment by Bocian-1** [comment]
Fixed in v2.19.2
