### ISSUE TITLE
Wall Maintenance Provider - inserter stops working

### ISSUE THREAD

**Issue by arutkowski00** [Opinionated-Blueprints/10-Books-Full-of-Rails#73]
### Have you checked the following resources?

- [x] [Wiki](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/wiki)
- [x] [Discussions Forum](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/discussions)
- [x] [Open and Closed Issues](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/issues)

### Version of the Book

v2.19.2

### Bug Description

If the inserter is holding a stack of certain items, but the train is already full, it stops inserting other items.

### How to reproduce the problem

1. Place down Wall Maintenance Provider blueprint.
2. Wait for the logistic network to provide all the items.
3. The inserter will start inserting the items (mine is having the stack capacity of 12).
4. If the train fills out with items of that type, but the inserter is still holding the remainder, it will no longer input any other items.
![Screenshot From 2024-11-22 23-05-51](https://github.com/user-attachments/assets/85d94596-52ae-46a9-90d4-43dcaec0feb1)
![Screenshot From 2024-11-22 23-05-39](https://github.com/user-attachments/assets/e5be93de-dbb3-4e3c-8c8a-4123f2b487ae)

### What did you expect?

The inserter should fill out the whole cargo wagon.

### What happened instead?

The inserter grabbed too many walls and it got stuck, because it couldn't put more walls into the train.

**Comment by Bocian-1** [comment]
Looks like I didn't save the adjustment I made to the wall signal value in the constant combinator. All of them should align with the filters in the cargo wagon, so it should be 1.6k instead of 1.7k which leads to this issue.

**Comment by Bocian-1** [comment]
Fixed in [v2.20.0](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/releases/tag/v2.20.0)
