### ISSUE TITLE
The last pump at the 6 car outpost doesn't work

### ISSUE THREAD

**Issue by Ella-Stingray** [Opinionated-Blueprints/10-Books-Full-of-Rails#75]
### Have you checked the following resources?

- [X] [Wiki](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/wiki)
- [X] [Discussions Forum](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/discussions)
- [X] [Open and Closed Issues](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/issues)

### Version of the Book

v2.19.2

### Bug Description

The 4th wagon is not aligned with the third pump so it does not work

### How to reproduce the problem

Place 6 car outpost and fill up a 2-4-0 fluid train and when it gets to the station it won't align to last pump
![bug](https://github.com/user-attachments/assets/3ae44d3a-c042-4cf0-957b-762c204e186d)

### What did you expect?

All three pumps are working

### What happened instead?

The third pump of the 4th wagon is not working

**Comment by Bocian-1** [comment]
I extended the outposts by a tile so the last wagon doesn't stand on a turn ([v2.20.0](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/releases/tag/v2.20.0))
