### ISSUE TITLE
Provider Solids station conflicts with 1-4 car loaders

### ISSUE THREAD

**Issue by Raptord** [Opinionated-Blueprints/10-Books-Full-of-Rails#77]
### Have you checked the following resources?

- [X] [Wiki](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/wiki)
- [X] [Discussions Forum](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/discussions)
- [X] [Open and Closed Issues](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/issues)

### Version of the Book

v2.19.2

### Bug Description

Constant combinator from Provider Solids conflicts with Lamp from 1-4 car loaders when using single-engine trains

### How to reproduce the problem

1. Place "Provider Solids" station blueprint
2. Attempt to place any of the 1-4 car loader blueprints in the corresponding location where they would go next to the station
    * This will fail due to the constant combinator below the medium power pole being in the same spot as the lamp should go 

Demonstration with 3-car loader:
![image](https://github.com/user-attachments/assets/9fb3180e-a22d-49f3-b836-2a2382eba793)

### What did you expect?

Loader blueprint should be able to be placed

### What happened instead?

The blueprint cannot be placed due to the Constant Combinator from the station being in the same spot as the lamp from the loader blueprint

**Comment by Bocian-1** [comment]
I'll take out the conflicting lamp then

**Comment by Bocian-1** [comment]
Fixed in [v2.20.0](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/releases/tag/v2.20.0)
