### ISSUE TITLE
Brief description of the blueprint issue

### ISSUE THREAD

**Issue by emilydelorme** [Opinionated-Blueprints/10-Books-Full-of-Rails#78]
### Have you checked the following resources?

- [X] [Wiki](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/wiki)
- [X] [Discussions Forum](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/discussions)
- [X] [Open and Closed Issues](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/issues)

### Version of the Book

V2.19.2

### Bug Description

Miss alignement of the 6 car 6 statations

### How to reproduce the problem

- Place Aligned correctly city block like empty one
- Place 6 car 6 station city block
- See 14 blocs displacement

→ Could be fixed with snap to grid Y: -22 instead of Y:-8

### What did you expect?

Aligned with the rest of the blocks

### What happened instead?

Alignement missmatch

**Comment by Bocian-1** [comment]
It should be fixed now? ([v2.20.0](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/releases/tag/v2.20.0))
