### ISSUE TITLE
Brief description of the blueprint issue

### ISSUE THREAD

**Issue by drf-jpg** [Opinionated-Blueprints/10-Books-Full-of-Rails#81]
### Have you checked the following resources?

- [X] [Wiki](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/wiki)
- [X] [Discussions Forum](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/discussions)
- [X] [Open and Closed Issues](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/issues)

### Version of the Book

v2.21.0

### Bug Description

Inline Solid Requesters 1-1-0 Train 3 Stations does not set far filters

### How to reproduce the problem

1. Place the 1-1-0 Train 3 Stations requester blueprint.
2. Specify three separate ores (near: iron ore, middle: copper ore, far: coal).
3. Observe that the blueprint sets the filters on inserters in the 'far' lane to be iron ore.

I think this is because of the '1' parameter being used both at the top and bottom.

![image](https://github.com/user-attachments/assets/1576c95c-f40a-4e0d-b882-73c3da754654)

### What did you expect?

The three stations would have the proper parameters.

### What happened instead?

Iron is set in the filters for the inserters.

**Comment by Bocian-1** [comment]
Fixed for [v2.21.1](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/releases/tag/v2.21.1)
