### ISSUE TITLE
Duplicate constant combinator in inline station for size 2 trains

### ISSUE THREAD

**Issue by drf-jpg** [Opinionated-Blueprints/10-Books-Full-of-Rails#86]
### Have you checked the following resources?

- [X] [Wiki](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/wiki)
- [X] [Discussions Forum](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/discussions)
- [X] [Open and Closed Issues](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/issues)

### Version of the Book

v2.21.1

### Bug Description

There are two constant combinators connected to the inline providers 1-1-0 Train 1 Station (R) variant.

### How to reproduce the problem

See attached image. It seems to be doubling up the value of 'T', for example--so that its train limit never falls below 1. This leaves trains deadlocked until the buffer chests are consumed.

![image](https://github.com/user-attachments/assets/ab362c0e-4e27-4af4-b02c-b60dfd71d280)

![image](https://github.com/user-attachments/assets/30df95e4-2555-4feb-b80e-706adf991127)

### What did you expect?

The train station limit should be set proportionally to the amount of buffer space.

### What happened instead?

Even with full buffers, the train limit is set to 1.

**Comment by Bocian-1** [comment]
Fixed on [v2.21.2](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/releases)
