### ISSUE TITLE
City Block does not align with existing rail blueprints nor does it have an exit onto existing rail networks

### ISSUE THREAD

**Issue by cherubael1010** [Opinionated-Blueprints/10-Books-Full-of-Rails#87]
### Have you checked the following resources?

- [X] [Wiki](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/wiki)
- [X] [Discussions Forum](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/discussions)
- [X] [Open and Closed Issues](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/issues)

### Version of the Book

2.19

### Bug Description

N/A

### How to reproduce the problem

![image](https://github.com/user-attachments/assets/affa8840-c4a7-4a63-b2c8-89f411147592)

### What did you expect?

city block rail systems to align with existing BP's

### What happened instead?

they don't :(

**Comment by Bocian-1** [comment]
Ah, these. I thought for a moment you mean the regular ones. I lil offset will fix that when I can get back to it

**Comment by Bocian-1** [comment]
Ah, you're on 2.19, I didn't notice. This has been since fixed, but it was the cityblock that needed an adjustment, not the segments.
