### ISSUE TITLE
Wrong constants for Inline Fluid Requester 2-4-0 3-Station

### ISSUE THREAD

**Issue by baumjamin** [Opinionated-Blueprints/10-Books-Full-of-Rails#89]
### Have you checked the following resources?

- [X] [Wiki](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/wiki)
- [X] [Discussions Forum](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/discussions)
- [X] [Open and Closed Issues](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/issues)

### Version of the Book

2.21.1

### Bug Description

Inline Fluid Requester 2-4-0 3 Station has wrong constants

### How to reproduce the problem

**Inline Fluid Requester 2-4-0 3 Station**
The constant combinators for inline fluid requester seem to be wrong: 

- V (fluid wagon volume) is set to 1 (should be 25k)
- B is set to 20 (should be 4 or 2, depending on left/middle/right)
- H is set to 48 (should be 50k)
![image](https://github.com/user-attachments/assets/9efdb669-9f18-4bed-b777-46071333421a)

Also: there seems to be a wrong formula or parameters are missing:
![image](https://github.com/user-attachments/assets/1093a3df-e08f-46da-9cac-ebdd639a43aa)

### What did you expect?

Corrent values

### What happened instead?

Values were wrong

**Comment by Bocian-1** [comment]
Fixed for [v2.21.2](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/releases). They were all broken, my bad for not checking after making changes
