### ISSUE TITLE
Blueprint string exceeds Factorio's maximum BP string length

### ISSUE THREAD

**Issue by nicholasgower** [Opinionated-Blueprints/10-Books-Full-of-Rails#97]
### Have you checked the following resources?

- [x] [Wiki](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/wiki)
- [x] [Discussions Forum](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/discussions)
- [x] [Open and Closed Issues](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/issues)

### Version of the Book

2.21.2

### Bug Description

Blueprint string fails to copy into Factorio 2.0.23

### How to reproduce the problem

1. Copy blueprint string into clipboard.
2. Attempt to copy the string into Factorio's "Import string" window.
3. Copy another shorter blueprint string.
Example string: 0eNrdWE1vozAQ/SuRjytTBQP54LD/YC+V9hRFyMCksRYwNSbbKMp/37EhkLakDcml215qxvab8RvPsyYHEmc1lEoUmoQHIhJZVCRcHUglngqeGVvBcyAhUZDskwwUOVIiihReSOge6dBCGctSKn22kB3XlEChhRbQwNuPfVTUeYyQoUvf7aaklBVukIXBRhDHC6aU7HGx7yO0gucaKh1tRKZBVWZRBYlZ33joYlwfTZhvHLLOYQ6pqHMHMtysROKUMoMh5/7sIWjdBw/BEKbXYaaQiBSUk8g8FgXXUg0izjvEGR4oFaqJn4QLSjARWsksimHLdwIBcFcLG+FcKtqTHsj5F557IxSy0mdF70sT0k4oXaOli7FZ4QBPtiZTJvGam1vgzqf4Zyx5yZUNPiQ/iUmhrHVZ67cX5GoP5R5DrwvMmZJ5JArEIuGGZxWYJA0w6ndYXAm9zUFjgj4hNRhJao/8htcbicRLiDBRzyczZMoSkEobB/lBTkyORR8kKaDvSnTw+rasLN+xIjTkbc2kZ3X8jHGgHyeXaZ2B49l6bpaa6sL87TASqfZtuXVfmDU8evKHhFMT7uCMe3GGXZzxzC1ZDzAwu44B//syMO8Y2PBKO6KoQOlLF+FUIIGLOvaaigHoRV+DuGoHTqnkrlG3LervxzVoXQyALkfE64+L153eELD3WcDu2QvVPDwf4vUcMxvzkPAkQiW10BHeLojkJjqTCHR2mu00KYKCxxmkJ8W89wV0b3gCg1fHGgL1RtHk/wc0+eNp8j6laZxmB8H3Uyx3nGh/SwpuU+35VSp4n2zPL9zb23T7qojZfbp9IWJ2q24vvqogsbt0e3GBplt1++vSdJduW5qw4fmLd9Z4W7nUpR5113TFaEDx7Qxw6KHJt0bfTLp2aP5R1+vHrLXbjb7daMesATEmyho7s+tbP+xkxzhMI4Y9iqVh1TUL7VnpaRCSpnfru4df/GVSoSDxJ5jEsJEKJo3aiuKJGNYuIrFzmMcmFRPbvdlO0CgqTvQ/HlCS8RiwlSG/CyxeVfFs8tgLu7FYroMZW/rLZeAv2WLmT4/Hf6uLgBM=
4. Attempt to copy the shorter string into Factorio's "Import string" window.

### What did you expect?

I expected both strings(Rail book and test string) to copy into the game.

### What happened instead?

The railbook string failed to copy into the game.

**Comment by Bocian-1** [comment]
I did just that right now with the latest version and it copied fine. 
I was also able to import it with 3 additional copies of itself inserted into it with no issues besides the game freezing for a few seconds.
Maybe you're inputting another character by accident and it breaks.

**Comment by brandon-gradient** [comment]
@nicholasgower the program being used to open the `.txt` file might be the issue.
windows has `clip < file.txt` and I'd assume basic "notepad.exe" should work. For mac I know TextEdit doesn't cause issues.
