### ISSUE TITLE
Ground Entry/Exit Overpass Entry and Overpass Exit's names are swapped

### ISSUE THREAD

**Issue by Secrean** [Opinionated-Blueprints/10-Books-Full-of-Rails#98]
### Have you checked the following resources?

- [x] [Wiki](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/wiki)
- [x] [Discussions Forum](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/discussions)
- [x] [Open and Closed Issues](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/issues)

### Version of the Book

v2.21.2

### Bug Description

Overpass Entry and Overpass Exit have the wrong names

### How to reproduce the problem

Steps to reproduce (or see issue):
1. Open Rails book
2. Go to Ground Entry/Exit
3. Try using Exit Overpass and Entry Overpass
![image](https://github.com/user-attachments/assets/f987fcae-0554-4d87-8b5b-ff86b3a3dd23)
![image](https://github.com/user-attachments/assets/d34f9931-a14f-4022-85d9-5fabd673094d)

### What did you expect?

Expected Exit Overpass to be an exit and Entry Overpass to be an entry 

### What happened instead?

Exit Overpass is actually an entry and Entry Overpass is actually an Exit

**Comment by Bocian-1** [comment]
Fixed on [v2.20.0 pre-release](https://github.com/Opinionated-Blueprints/10-Books-Full-of-Rails/releases)
